# Generated by Django 2.2.20 on 2021-04-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hraci',
            fields=[
                ('hrac_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Prezdivka', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Servery',
            fields=[
                ('server_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=25)),
                ('game_port', models.CharField(max_length=10)),
                ('query_port', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Moderovani',
            fields=[
                ('incident_id', models.IntegerField(primary_key=True, serialize=False)),
                ('provineni', models.CharField(max_length=20)),
                ('postih', models.CharField(max_length=20)),
                ('datum_incidentu', models.DateTimeField()),
                ('datum_odebrani_trestu', models.DateTimeField()),
                ('hrac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hraci')),
                ('server_id', models.ForeignKey(on_delete=None, to='app.Servery')),
            ],
        ),
        migrations.CreateModel(
            name='Bugy',
            fields=[
                ('bug_id', models.IntegerField(primary_key=True, serialize=False)),
                ('typ_bugu', models.CharField(max_length=20)),
                ('vyreseny', models.BooleanField()),
                ('popis', models.CharField(max_length=150)),
                ('poskozeni', models.CharField(max_length=70)),
                ('hrac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hraci')),
                ('server_id', models.ForeignKey(on_delete=None, to='app.Servery')),
            ],
        ),
        migrations.CreateModel(
            name='Bany',
            fields=[
                ('ban_id', models.IntegerField(primary_key=True, serialize=False)),
                ('typ_banu', models.CharField(max_length=20)),
                ('zabanovany', models.BooleanField()),
                ('datum_banu', models.DateTimeField()),
                ('datum_odbanovani', models.DateTimeField()),
                ('duvod', models.TextField(max_length=50)),
                ('hrac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hraci')),
                ('server_id', models.ForeignKey(on_delete=None, to='app.Servery')),
            ],
        ),
    ]
