# Generated by Django 2.2.20 on 2021-04-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210423_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bany',
            options={'verbose_name': 'Ban', 'verbose_name_plural': 'Bany'},
        ),
        migrations.AlterModelOptions(
            name='bugy',
            options={'verbose_name': 'Bug', 'verbose_name_plural': 'Bugy'},
        ),
        migrations.AlterModelOptions(
            name='hraci',
            options={'verbose_name': 'Hráč', 'verbose_name_plural': 'Hráči'},
        ),
        migrations.AlterModelOptions(
            name='moderovani',
            options={'verbose_name': 'Moderovani', 'verbose_name_plural': 'Moderovani'},
        ),
        migrations.AlterModelOptions(
            name='servery',
            options={'verbose_name': 'Server', 'verbose_name_plural': 'Servery'},
        ),
        migrations.AlterModelOptions(
            name='typy_banu',
            options={'verbose_name': 'Typ banu', 'verbose_name_plural': 'Typy banů'},
        ),
        migrations.AlterModelOptions(
            name='typy_bugu',
            options={'verbose_name': 'Typ bugu', 'verbose_name_plural': 'Typy bugů'},
        ),
    ]
