# Generated by Django 2.2.20 on 2021-04-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210423_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='servery',
            name='zeme',
            field=models.CharField(default='Česko', max_length=50),
            preserve_default=False,
        ),
    ]
