# Generated by Django 2.2.20 on 2021-04-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210423_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulare',
            fields=[
                ('form_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'formulář',
                'verbose_name_plural': 'formuláře',
            },
        ),
    ]
