# Generated by Django 2.2.20 on 2021-04-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_formulare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulare',
            options={'verbose_name': 'formular', 'verbose_name_plural': 'formulare'},
        ),
    ]
