# Generated by Django 2.2.20 on 2021-04-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210428_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bany',
            name='datum_banu',
            field=models.DateTimeField(default='YYYY-MM-DD HH:mm:SS'),
        ),
        migrations.AlterField(
            model_name='bany',
            name='datum_odbanovani',
            field=models.DateTimeField(blank=True, default='YYYY-MM-DD HH:mm:SS', null=True),
        ),
        migrations.AlterField(
            model_name='moderovani',
            name='datum_incidentu',
            field=models.DateTimeField(default='YYYY-MM-DD HH:mm:SS'),
        ),
        migrations.AlterField(
            model_name='moderovani',
            name='datum_odebrani_trestu',
            field=models.DateTimeField(blank=True, default='YYYY-MM-DD HH:mm:SS', null=True),
        ),
        migrations.AlterField(
            model_name='moderovani',
            name='provineni',
            field=models.CharField(max_length=40),
        ),
    ]
