# Generated by Django 2.2.20 on 2021-04-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210429_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugy',
            name='poskozeni',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
